server:
  port: 8080

# 日志
logging:
  config.classpath: log4j2.xml
  level.cn.jay.repository: trace

#================数据源配置==================#
spring:
  datasource:
    name: mydb
    url: jdbc:mysql://localhost:3306/hotdog?useUnicode=true&useSSL=false&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 200
    timeBetweenEvictionRunsMillis: 1800000
    minEvictableIdleTimeMillis: 1800000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: falsemysql-connector-java
    testOnReturn: false

# Redis数据库索引（默认为0）
spring.redis.database: 0
# Redis服务器地址
spring.redis.host: 127.0.0.1
# Redis服务器连接端口
spring.redis.port: 6379
# Redis服务器连接密码（默认为空）
spring.redis.password:
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-active: 20
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait: -1
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-idle: 10
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle: 0
# 连接超时时间（毫秒）
spring.redis.timeout: 1000